use std::fmt::{Display, Write};

use crate::Token;

impl Display for Token<'_> {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        use Token::*;
        let lit = match self {
            Ident(i) => i,
            As => "as",
            At(directive) => {
                f.write_char('@')?;
                directive
            }
            Elif => "elif",
            Return => "return",
            Break => "break",
            Void => "void",
            Continue => "continue",
            Struct => "struct",
            Enum => "enum",
            Pub => "pub",
            Char => "Char",
            Int => "int",
            UInt => "uint",
            Float => "float",
            Str => "str",
            Double => "double",
            Bool => "bool",
            Output => "output",
            Outputln => "outputln",
            Const => "const",
            Alloc => "alloc",
            Free => "free",
            Sizeof => "sizeof",
            Defer => "defer",
            In => "in",
            Switch => "switch",
            Fn => "fn",
            Let => "let",
            If => "if",
            Else => "else",
            Loop => "loop",
            Cast => "cast",
            BoolLit(true) => "true",
            BoolLit(false) => "false",
            IntLit(v) => return v.fmt(f),
            FloatLit(v) => return v.fmt(f),
            StringLit(s) => return write!(f, "{s:?}"),
            CharLiteral(c) => return c.fmt(f),
            Tilde => "~",
            Question => "?",
            LShift => "<<",
            RShift => ">>",
            RArrow => "=>",
            EqEq => "==",
            Ne => "==",
            Le => "==",
            Ge => "==",
            And => "&&",
            Or => "||",
            Ampersand => "&",
            BitXor => "^",
            BitOr => "|",
            Lt => "<",
            Gt => ">",
            Percent => "%",
            PlusPlus => "++",
            Plus => "+",
            MinusMinus => "--",
            Minus => "-",
            Star => "*",
            Slash => "/",
            ColonColon => "::",
            Colon => ":",
            LParen => "(",
            RParen => ")",
            LBrace => "{",
            RBrace => "}",
            LBracket => "[",
            RBracket => "]",
            Comma => ",",
            Semicolon => ";",
            Range => "..",
            Dot => ".",
            Eq => "=",
            Not => "!",
        };
        f.write_str(lit)
    }
}
